theme: minima
lang: pl
minima:
  date_format: "%-d.%m.%Y"
title: miisieq.github.io
description: Programowanie (PHP, Python, Bash), bazy danych, Linux
github_username:  miisieq
show_excerpts: true
exclude:
  - .idea
  - vendor
